### ISSUE TITLE
[Bug] Add Link checker

### ISSUE THREAD

**Issue by Mr-Sunglasses** [FOSS-Community/LinkLiberate#5]
## Description

Currently we can liberate any text but the problem is it does not check if the it is link or not

## Reproduction

1. 
2. 
3. 
4. See error.

## Expectation

Add some logic to identify weather it is a link or not.

## Environment

- Device: (_eg._ iPhone Xs; laptop)
- OS: (_eg._ iOS 13.5; Fedora 32)
- Browser: (_eg._ Safari; Firefox)
- Version: (_eg._ 13; 73)
- Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by SAMAD101** [comment]
done
