### ISSUE TITLE
[Feature] URL expiration

### ISSUE THREAD

**Issue by SAMAD101** [FOSS-Community/LinkLiberate#7]
## Description

Add URL expiration.
Not to be implemented on all the URLs. 
Could be turned on/off by the creator of the shortened URL.
Feature to manipulate the duration of time (by the creator of the shortened URL)  after which the URL will expire.

## Alternatives
Suggestions are welcome.

**Comment by hemant933** [comment]
i wanna try it , assign it to me plz

**Comment by SAMAD101** [comment]
> i wanna try it , assign it to me plz

sure, go ahead
